name: CI - Build & Push

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write   # required for OIDC
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ECR_REPO: mini-cicd-app

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Configure AWS credentials using OIDC (recommended) -> no long-lived keys
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::123456789012:role/GitHubActionsRole
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO }}:latest

      - name: Output image name
        run: echo "IMAGE=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO }}:latest" >> $GITHUB_ENV
